import { getConfigValue } from '../util.js';

export const singleSessionEnabled = !!getConfigValue('singleSession', true, 'boolean');

// Background tabs may throttle the 10-second heartbeat to roughly one minute.
const SESSION_TIMEOUT_MS = 90 * 1000;

/** @type {Map<string, {id: string, generation: number, lastSeen: number}>} */
const activeSessions = new Map();

/** @type {Map<string, Map<string, {count: number, waiters: Set<() => void>}>>} */
const pendingRequests = new Map();

/**
 * Claims a page session for a user. A forced claim fences the old page before
 * waiting for its admitted writes, so takeover cannot reorder stale saves.
 * @param {string} handle User handle
 * @param {string} sessionId Unique ID generated by the browser page
 * @param {boolean} force Whether to replace an existing session
 * @returns {Promise<{conflict?: boolean, revoked?: boolean, generation: number}>}
 */
export async function claimTabSession(handle, sessionId, force = false) {
    const active = activeSessions.get(handle);

    if (active?.id === sessionId) {
        active.lastSeen = Date.now();
        return { generation: active.generation };
    }

    const activeRecently = active && Date.now() - active.lastSeen < SESSION_TIMEOUT_MS;
    if (activeRecently && !force) {
        return { conflict: true, generation: active.generation };
    }

    const generation = (active?.generation ?? 0) + 1;
    activeSessions.set(handle, { id: sessionId, generation, lastSeen: Date.now() });

    if (active) {
        await waitForPendingRequests(handle, active.id);
    }

    const current = activeSessions.get(handle);
    if (current?.id !== sessionId || current.generation !== generation) {
        return { revoked: true, generation };
    }

    return { generation };
}

/**
 * Rejects browser API requests that do not belong to the active page session.
 * Requests without a page-session header are treated as external API clients.
 * @type {import('express').RequestHandler}
 */
export function tabSessionMiddleware(request, response, next) {
    const handle = request.user?.profile?.handle;
    const csrfToken = request.headers['x-csrf-token']?.toString();
    const sessionId = request.headers['x-st-session-id']?.toString();

    if (!singleSessionEnabled || !handle || !csrfToken || !sessionId) {
        return next();
    }

    const active = activeSessions.get(handle);

    if (active?.id !== sessionId) {
        response.set('X-ST-Session-Revoked', '1');
        return response.status(409).send({ error: 'tab-session-revoked' });
    }

    active.lastSeen = Date.now();
    const isGenerationRequest = /(?:^|\/)generate(?:[-/]|$)/.test(request.path);
    const isPersistentWrite = !['GET', 'HEAD', 'OPTIONS'].includes(request.method)
        && request.path !== '/ping'
        && !isGenerationRequest;
    if (isPersistentWrite) {
        trackPendingRequest(handle, sessionId, response);
    }

    return next();
}

/**
 * Tracks an admitted state-changing request until its response is complete.
 * @param {string} handle User handle
 * @param {string} sessionId Page session ID
 * @param {import('express').Response} response Express response
 */
function trackPendingRequest(handle, sessionId, response) {
    let userRequests = pendingRequests.get(handle);
    if (!userRequests) {
        userRequests = new Map();
        pendingRequests.set(handle, userRequests);
    }

    let sessionRequests = userRequests.get(sessionId);
    if (!sessionRequests) {
        sessionRequests = { count: 0, waiters: new Set() };
        userRequests.set(sessionId, sessionRequests);
    }

    sessionRequests.count++;
    let released = false;
    const release = () => {
        if (released) {
            return;
        }

        released = true;
        sessionRequests.count--;
        if (sessionRequests.count > 0) {
            return;
        }

        userRequests.delete(sessionId);
        if (userRequests.size === 0) {
            pendingRequests.delete(handle);
        }
        for (const resolve of sessionRequests.waiters) {
            resolve();
        }
    };

    response.once('finish', release);
    response.once('close', release);
}

/**
 * Waits for requests admitted before a takeover to finish.
 * @param {string} handle User handle
 * @param {string} sessionId Superseded page session ID
 * @returns {Promise<void>}
 */
function waitForPendingRequests(handle, sessionId) {
    const sessionRequests = pendingRequests.get(handle)?.get(sessionId);
    if (!sessionRequests?.count) {
        return Promise.resolve();
    }

    return new Promise(resolve => sessionRequests.waiters.add(resolve));
}
